Shop/urls.py
from django.urls import path,re_path

from . import views
app_name = 'MyShop'
urlpatterns = [
    path('', views.ProductView.as_view(), name='product_list'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('cart/remove<int:product_id>/', views.cart_remove, name='cart_remove'),
    re_path(r'.*register/$', views.RegisterFormView.as_view(), name='register'),
    re_path(r'.*login/$', views.LoginFormView.as_view(), name='login'),
    re_path(r'.*logout/$', views.LogoutView.as_view(), name='logout'),
    re_path(r'.*search/$', views.SearchResultsView.as_view(), name='search_results'),
    path('create/', views.order_create, name='order_create'),
    path('<slug:category_slug>/', views.ProductView.as_view(), name='product_list_by_category'),
    path('<int:id>/<slug:slug>', views.ProductDetail.as_view(), name='product_detail'),



]

djangoProjectShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Shop.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Категория')
    slug = models.SlugField(max_length=200, unique=True, null=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('MyShop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    name = models.CharField(max_length=200, unique=True, verbose_name='Товар')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория')
    description = models.CharField(max_length=1000, verbose_name='Описание')
    image = models.ImageField(verbose_name='Картинка', upload_to='image/', default='default.jpg')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    slug = models.SlugField(max_length=200, unique=True, null=True)

    class Meta:
        ordering = ('category',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('MyShop:product_detail', args=[self.id, self.slug])


class Commentary(models.Model):
    name = models.CharField(max_length=500, verbose_name='Комментарий', null=True)
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='Товар', related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Пользователь', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.name


class ReviewedProducts(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='Товар', related_name='rev_prod')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='Пользователь', on_delete=models.CASCADE, null=True)
    url = models.CharField(max_length=200, null=True)

    class Meta:
        ordering = ('-date',)
        verbose_name = 'Просмотренные товары'


class Order(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    email = models.EmailField()
    address = models.CharField(max_length=250, verbose_name='Адрес')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')
    paid = models.BooleanField(default=False, verbose_name='Оплачен')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE, verbose_name='Товар')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    def __str__(self):
        return f'{self.id}'

    def get_cost(self):
        return self.price * self.quantity

Shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Order, Commentary


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Commentary
        fields = ('name',)

Shop/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import View, ListView, DetailView, CreateView, FormView
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from .forms import *
from django.views.decorators.http import require_POST
from .cart import Cart


class ProductView(View):
    def get(self, request, category_slug=None):
        product = Product.objects.all()
        category = None
        categories = Category.objects.all()
        revprod = ReviewedProducts.objects.order_by('-date')[:5]
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            product = product.filter(category=category)

        return render(request, 'product/list.html',
                      {'product_list': product, 'category': category, 'categories': categories,
                       'title': 'Главная страница', 'revprod': revprod})


class ProductDetail(DetailView):
    def get(self, request, id, slug):
        product = get_object_or_404(Product, id=id, slug=slug)
        cart_product_form = CartAddProductForm()
        comments = product.comments.all()
        comment_form = CommentForm()
        if ReviewedProducts.objects.first() is None:
            last = 'none'
        else:
            last = ReviewedProducts.objects.first().product.name
        if product.name != last:
            ReviewedProducts.objects.create(product=product, url=product.get_absolute_url())
        return render(request, 'product/detail.html', {'product': product,
                                                       'cart_product_form': cart_product_form,
                                                       'comments': comments, 'comment_form': comment_form})

    def post(self,request,id,slug):
        product = get_object_or_404(Product, id=id, slug=slug)
        cart_product_form = CartAddProductForm()
        comments = product.comments.all()
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.product = product
            new_comment.user = request.user
            new_comment.save()
        return render(request, 'product/detail.html', {'product': product,
                                                       'cart_product_form': cart_product_form,
                                                       'comments': comments, 'comment_form': comment_form})


class RegisterFormView(FormView):
    form_class = UserCreateForm
    success_url = '/login/'
    template_name = 'product/register.html'

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

    def form_invalid(self, form):
        return super(RegisterFormView,self).form_invalid(form)


class LoginFormView(FormView):
    form_class = AuthenticationForm
    template_name = 'product/login.html'
    success_url = '/'

    def form_valid(self, form):
        self.user = form.get_user()
        login(self.request, self.user)
        return super(LoginFormView, self).form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')


class SearchResultsView(ListView):
    model = Product
    template_name = 'product/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(Q(name__icontains=query))
        return object_list


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('MyShop:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('MyShop:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'product/cart_detail.html', {'cart': cart})


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()
            return render(request,'product/created.html', {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'product/create.html', {'cart': cart, 'form': form})

Shop/templates/product/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой первый магазин{% endblock %}</title>
    <link href="{% static 'myshop/css/base.css' %}" rel="stylesheet">
</head>
<body>
<div id="header">
<a href="/" class="logo">Мой первый магазин</a>
</div>
<div id="subheader" >
{% with total_items=cart|length %}
        {% if cart|length > 0 %}
            В Вашей корзине :
            <a href="{% url "MyShop:cart_detail" %}">
                {{ total_items }} ед. товара,
                на общую сумму {{ cart.get_total_price }} грн.
            </a>
        {% else %}
            Ваша корзина пуста
        {% endif %}
    {% endwith %}
<p>

</p>
<form action="{% url 'MyShop:search_results' %}" method="get">
        <input name="q" type="text" placeholder="Поиск...">
    </form>

    <div style="text-align: right">
        {% if user.is_authenticated %}
        <a href="logout/">Выйти({{user.username}})</a>
        {% else %}
        <a href="register/">Регистрация</a> | <a href="login/">Войти</a>
        {% endif %}
    </div>
</div>
<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
</html>

Shop/templates/product/cart_detail.html
{% extends 'product/base.html' %}
{% load static %}
{% block title %}
    Ваша корзина покупок
{% endblock %}
{% block content %}
    <h1>Ваша корзина покупок</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Цена единицы</th>
            <th>Сумма</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "images/no_image.png" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "MyShop:cart_remove" product.id %}">Удалить</a></td>
                    <td class="num">{{ item.price }} грн.</td>
                    <td class="num">{{ item.total_price }} грн.</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} грн.</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        {% if user.is_authenticated %}
        <a href="{% url "MyShop:product_list" %}" class="button light">Продолжить покупки</a>
        <a href="{% url 'MyShop:order_create' %}" class="button">Оформить заказ</a>
    {% else %}
    <a href="/" class="button">Для оформления заказа необходимо зарегистрироваться </a>
    </p>
    {% endif %}

{% endblock %}

Shop/templates/product/create.html
{% extends 'product/base.html' %}
{% block title %}Оформление заказа{% endblock %}
{% block content %}
    <h1>Оформление заказа</h1>
    <div class="order-info">
    <h3>Ваш заказ</h3>
    <ul>
        {% for item in cart %}
        <li>
            {{ item.quantity }}x{{ item.product.name }}
            <span>{{ item.total_price }} грн.</span>
        </li>
        {% endfor %}
    </ul>
    <p>Итого:{{ cart.get_total_price }}</p>
    </div>
    <form action="." method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Разместить заказ"></p>
    {% csrf_token %}
    </form>

{% endblock %}

Shop/templates/product/created.html
{% extends 'product/base.html' %}
{% block title %}Спасибо{% endblock %}
{% block content %}
    <h1>Спасибо</h1>
    <p>Ваш заказ сформирован. Вашему заказу присвоен номер
    <strong>{{ order.id }}</strong></p>
{% endblock %}

Shop/templates/product/detail.html
{% extends "product/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static "myshop/images/default.jpg" %}{% endif %}">
<h1>{{ product.name }}</h1>
<h2>
<a href="{{ product.category.get_absolute_url }}">{{product.category }}</a>
</h2>
<p class="price">{{ product.price }} грн.</p>

{{ product.description|linebreaks }}
<form action="{% url 'MyShop:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Добавить в корзину">
</form>
<br>
<br>

    <a href="/">На главную страницу</a>
</div>
    <div class="feedback">
    {% with comments.count as total_comments %}
    <h2>
    {{ total_comments }} комментариев
    </h2>
    {% endwith %}
    {% for comment in comments %}
        <div>
        <p>
            Комментарий {{ forloop.counter }} создан {{ comment.date }} пользователем {{ comment.user }}
        </p>
        {{ comment.name|linebreaks }}
        </div>
    {% empty %}
        <p>У данного товара пока нет отзывов</p>
    {% endfor %}
{% if user.is_authenticated %}
{% if new_comment %}

    <h2>Ваш комментарий добавлен</h2>
    {% else %}
    <h2>Добавить новый комментарий</h2>
    <form action="" method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Добавьте комментарий"></p>
    </form>
    {% endif %}
{% else %}
    <br>
    <br>
<p>Отзывы могут оставлять только зарегистрированные пользователи</p>
    </div>
{% endif %}
{% endblock %}

Shop/templates/product/list.html
{% extends 'product/base.html' %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
    <h3>Категория</h3>
    <ul>
        <li {% if not category %}class="selected" {% endif %}>
            <a href="{% url "MyShop:product_list" %}">Все</a>
        </li>
        {% for cat in categories %}
        <li {% if category.slug == cat.slug %}class="selected" {% endif %}>
            <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
        {% endfor %}
    </ul>
<br>
<br>
<h3>Просмотренные товары</h3>

    <ul>
        {% for prod in revprod %}
        <li>
        <a href="{{ prod.url }}">{{ prod.product }}</a>

        </li>
        {% endfor %}
    </ul>
</div>
<div id="main" class="product-list">
    <h1 class="item1">{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    {% for p in product_list %}
    <div class="item">
        <a href="{{ p.get_absolute_url }}">
            <img src="{% if p.image %}{{ p.image.url }}{% else %}{% static 'myshop/images/no_image.jpg' %}{% endif %}">
        </a>
        <a href="{{ p.get_absolute_url }}">{{ p.name }}</a>
        <br>
        {{ p.price }} грн.
    </div>
    {% endfor %}
</div>

{% endblock %}

Shop/templates/product/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <label for="">{{field.label}}</label>
        <div>{{field}}</div>
        {% if field.errors %}
        <p>{{field.errors}}</p>
        {% endif %}
        {% endfor %}
        <button type="submit">Войти</button>
    </form>

</body>
</html>

Shop/templates/product/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Регистрация</title>
</head>
<body>


    <form action="" method="post">{% csrf_token %}
        {% for field in form %}
        <label for="">{{field.label}}</label>
        <div>{{field}}</div>
        {% if field.errors %}
        <p>{{field.errors}}</p>
        {% endif %}
        {% endfor %}
    <button type="submit">Зарегистрироваться</button>
    </form>
</body>
</html>

Shop/templates/product/search_results.html
{% extends 'product/base.html' %}
{% load static %}
{% block title %}
    Результаты поиска
{% endblock %}
{% block content %}
<h1>Результаты поиска</h1>
  <ul>
    {% for product in object_list %}
      <li>
        <a href="{{ product.get_absolute_url }}">{{product.name}}</a>
      </li>
    {% endfor %}
  </ul>
<div>
    <a href="/">На главную</a>
</div>
{% endblock %}